name: Test

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:

  test-default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create Microshift cluster
        uses: ./

      - name: Test
        run: |
          sleep 1m
          oc version
          oc cluster-info
          oc wait --for=condition=Ready nodes --all --timeout=300s
          oc describe nodes
          oc wait --for=condition=Ready pods --all -A --timeout=300s
          oc get pods -A

  test-with-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create Microshift cluster with custom version
        uses: ./
        with:
          version: "4.7.0-0.microshift-2021-08-10-163759"

      - name: Test
        run: |
          sleep 1m
          oc version
          oc cluster-info
          oc wait --for=condition=Ready nodes --all --timeout=300s
          oc describe nodes
          oc wait --for=condition=Ready pods --all -A --timeout=300s
          oc get pods -A
